default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: colyer_me_dev
test:
  <<: *default
  database: colyer_me_test
production:
  <<: *default
  database: colyer_me
  username: colyer_me
  password: <%= ENV['COLYER_ME_DATABASE_PASSWORD'] %>

